steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'us-west2-docker.pkg.dev/unseenphotogallery/docker-unseen/unseen-exhibition-web', '.' ]
- name: node
  entrypoint: npm
  args: ['run', 'build']

images:
- 'us-west2-docker.pkg.dev/unseenphotogallery/docker-unseen/unseen-exhibition-web'