# Generated by Django 3.2.13 on 2022-06-01 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=256)),
                ('last_name', models.CharField(max_length=256)),
                ('email', models.EmailField(blank=True, max_length=256)),
                ('response', models.CharField(help_text='Max. 75 Characters', max_length=75)),
                ('consent_to_share', models.BooleanField(blank=True, help_text='Consent to OSF to use response in social media.')),
                ('featured', models.BooleanField(blank=True, help_text='Featured comments will have special styling.')),
            ],
        ),
        migrations.AddField(
            model_name='photo',
            name='photo',
            field=models.ImageField(default=None, upload_to=''),
            preserve_default=False,
        ),
    ]
