# Generated by Django 3.2.13 on 2022-06-01 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_photo_and_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='gallery.photo'),
        ),
    ]
