# Generated by Django 3.2.13 on 2022-06-09 18:32

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_connect_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='default', editable=False, populate_from='name'),
            preserve_default=False,
        ),
    ]
