# Generated by Django 3.2.13 on 2022-06-17 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['sort_order']},
        ),
        migrations.AddField(
            model_name='photo',
            name='sort_order',
            field=models.IntegerField(blank=True, db_index=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='photo',
            name='name',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
