# Generated by Django 3.2.13 on 2022-06-01 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_remove_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='social_image',
            field=models.ImageField(default=None, upload_to='', null=True, blank=True),
            preserve_default=False,
        ),
    ]
